apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-stage
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: d+offpeak-stage@hogborg.se
    privateKeySecretRef:
      name: letsencrypt-stage
    http01: {}

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: d+offpeak-prod@hogborg.se
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
